name: Build docker

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.pkg.github.com/countstarlight/arch-makepkg-action/makepkg
      DOCKERHUB_IMAGE: countstarlight/makepkg
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Login docker registry
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u countstarlight -p $DOCKER_TOKEN
    - name: Build docker image
      run: docker build --rm=true -t $DOCKERHUB_IMAGE:latest .
    - name: Push docker image
      run: |
        docker push $DOCKERHUB_IMAGE:latest
